### ISSUE TITLE
Add an option to disable executing on a specifc gamemode or ip.

### ISSUE THREAD

**Issue by Hazeofdream** [Vurv78/Safety#12]
Latest works fine in sandbox, tried to hop in a zombie survival server and COMPLETELY busted the game as result as this blocked the base gamemode.

I wouldn't doubt this may happen for other gamemodes, too? I also trust some servers so this should probably be a neccessary option.

**Comment by Hazeofdream** [comment]
Void that, breaks on Sandbox too now after trying to join ZS.

![image](https://user-images.githubusercontent.com/74027566/156497022-75ea0727-a30c-45b5-953f-117ce8e93387.png)

**Comment by Vurv78** [comment]
When the plugin system for autorun is implemented, hopefully this could be done, but right now there's no real way to do this besides touching the source code, and at that point you could just do it yourself

**Comment by Hazeofdream** [comment]
Apparently i can't even get this to run properly lmao.

**Comment by Vurv78** [comment]
It does break with servers with a lot of addons. One I know is pac because of their dumb bytecode scanner they have for some reason. Never tested outside of sandbox so that surely broke something. I mean when you have like 100 detours you're bound to break stuff. But this has needed a refactor and I'll hopefully get to that when these are more maintainable through plugins.

**Comment by Vurv78** [comment]
In the meantime you could just pick apart the parts you find necessary like the http detours and such

**Comment by Hazeofdream** [comment]
I figured that could be the case but my addons are exclusively gamemodes, hd remodels and building tools. most of the heavy stuff like acf and wire is mounted locally.

**Comment by Vurv78** [comment]
Done @Hazeofdream, you'll need the bleeding edge version of Autorun though

**Comment by Hazeofdream** [comment]
Works across gamemodes from what I've tested, not sure if the IP blacklist worked though as I got no feedback from it. not sure if it failed to log it or was not working.

**Comment by Vurv78** [comment]
Made it only print to your console, limited stack traceback size, and stopped using lua for the concommand blocklist (since I had a pattern 'play', this was blocked because of the 'display')

Also you should see in your console whether it's enabled now
![image](https://user-images.githubusercontent.com/56230599/156893641-1f9dd90f-8774-4221-99ba-a658c7552272.png)

**Comment by Hazeofdream** [comment]
Seems to delete egp objects and not sure exactly wire, Seems to break some misc wire functions.

![image](https://user-images.githubusercontent.com/74027566/156904239-295f9a23-02f3-4a44-9c8d-f7a10f74bcc2.png)

**Comment by Vurv78** [comment]
Looks like errors caused by something else happening earlier, would need to see even earlier stack traces if possible
